### ISSUE TITLE
Dashboard Performance Improvement & Missing Endpoints

### ISSUE THREAD

**Issue by Subomi** [frain-dev/convoy#1456]
**To-do**

- [x] Remove statistics from the project details endpoint.
- [x] Add new onboarding status to project details endpoint.
- [x] Add source details to the event delivery object.
